# src/main/resources/application.properties

# Base H2 en mémoire
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Voir les requêtes SQL dans la console (utile pour apprendre)
spring.jpa.show-sql=true

# Console H2 accessible sur /h2-console
spring.h2.console.enabled=true

# Crée/recrée les tables automatiquement
spring.jpa.hibernate.ddl-auto=create-drop
